services:
    php:
        container_name: laravel_giphy-php
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www
        depends_on:
            - db
        networks:
            - laravel

    nginx:
        container_name: laravel_giphy-nginx
        image: nginx:alpine
        ports:
            - "8080:80"
        volumes:
            - ./src:/var/www
            - ./etc/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - laravel

    db:
        container_name: laravel_giphy-db
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laraveluser
            MYSQL_PASSWORD: secret
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel
        healthcheck:
            test: [ "CMD", "mysqladmin", "--user=laraveluser", "--password=secret", "--host=127.0.0.1", "ping", "--silent" ]
            interval: 2s
            timeout: 10s
            retries: 10

    wiremock:
        image: wiremock/wiremock:latest
        container_name: wiremock
        ports:
            - "9001:8080"
        volumes:
            - ./tests/Core/Gifs/Infrastructure/Wiremock:/home/wiremock/mappings
        environment:
            - WIREMOCK_ROOT_DIRECTORY=/home/wiremock
        networks:
            - laravel

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
        container_name: elasticsearch
        environment:
            - discovery.type=single-node
            - xpack.security.enabled=false
            - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
        ports:
            - "9200:9200"
        networks:
            - laravel
            - elastic-network

    kibana:
        image: docker.elastic.co/kibana/kibana:8.9.0
        container_name: kibana
        environment:
            - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
        ports:
            - "5601:5601"
        depends_on:
            - elasticsearch
        volumes:
            - ./etc/docker/kibana:/data
        networks:
            - laravel
            - elastic-network

    kibana-importer:
        image: curlimages/curl:7.87.0
        container_name: kibana_importer
        depends_on:
            - kibana
        volumes:
            - ./etc/docker/kibana:/data
        entrypoint: [ "/bin/sh", "/data/entrypoint.sh" ]
        environment:
            - KIBANA_HOST=http://kibana:5601
        networks:
            - elastic-network
networks:
    laravel:
    elastic-network:
        driver: bridge

volumes:
    dbdata:
